config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebookAuth'

  get 'businesses/all' => 'businesses#all'

  resources :users
  resources :businesses

  resources :users, only: [:show] do
    resources :businesses, only: [:show, :index]
  end

  resources :businesses, only: [:show] do
    resources :comments
  end

  resources :businesses, only: [:show] do
    resources :tags
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
    belongs_to :users, dependent: :destroy, required: false
    has_many :comments, dependent: :destroy

    has_many :businesses_tags
    has_many :tags, through: :businesses_tags

    scope :latest, -> { order(created_at: :desc) }
end

app/models/businesses_tag.rb
class BusinessesTag < ApplicationRecord
    belongs_to :business, required: false
    belongs_to :tag, required: false
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :business
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :businesses_tags
    has_many :businesses, through: :businesses_tags

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :businesses
    has_many :comments, through: :businesses
    
    validates :email, presence: true
    validates :email, uniqueness: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include ApplicationHelper

    private

    def require_login
        if !logged_in?
            flash[:danger] = "You have to be logged in to view this page!"
            redirect_to '/'
        end
    end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
    before_action :require_login
    before_action :find_business, only: [:show, :edit, :update, :destroy]

    def index
        @businesses = current_user.businesses.all
        respond_to do |f|
            f.html { render :all }
            f.json { render json: @businesses }
        end
    end

    def all
        @businesses = Business.all
        respond_to do |f|
            f.html { render :all} 
            f.json { render json: @businesses }
        end
    end

    def show
        @comments = Comment.where(business_id: @business)
        respond_to do |format|
            format.html
            format.json {render json: @business}
        end
    end

    def new
        @business = Business.new
    end

    def create
        @business = current_user.businesses.build(business_params)

        if @business.save
            redirect_to user_business_path(current_user, @business)
        else
            redirect_to new_business_path
        end
    end

    def edit
    end

    def update
        if @business.update(business_params)
            redirect_to user_business_path(current_user, @business)
          else
            render :edit
        end
    end

    def destroy
        @business.destroy
        redirect_to businesses_path
    end

    private

    def business_params
        params.require(:business).permit(:name, :description, :address, :price, :user_id)
    end

    def find_business
        @business = Business.find(params[:id])
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @business = Business.find(params[:business_id])
        @comment = @business.comments.create(comment_params)
        @comment.user_id = current_user.id
        @comment.business_id = @business.id

        if @comment.save
            redirect_to user_business_path(@business.user_id, @business)
        else
            render :new
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :user_id, :business_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # Login Form
    def new
        @user = User.new
        if logged_in?
            flash[:message] = "You are alrady logged in"
            redirect_to user_path(current_user)
        else
            render 'new'
        end
    end

    # Normal Login
    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            flash[:success] = "Welcome #{@user.name}!"
            redirect_to user_path(current_user)
        else
            flash[:message] = "Please enter the correct information."
            redirect_to '/login'
        end
    end

    # Login with Facebook
    def facebookAuth
        @user = User.find_or_create_by(uid: auth['uid']) do |u|
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(10)
        end
        session[:user_id] = @user.id
        flash[:success] = "Welcome #{@user.name}!"
        redirect_to user_path(@user)

    end

    # Logout
    def destroy
        session.clear
        flash[:success] = "You have logged out"
        redirect_to '/'
    end

    private
    
    def user_params
        params.require(:users).permit(:username, :email, :password)
    end

    def auth
        request.env['omniauth.auth']
    end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def create
        @business = Business.find(params[:business_id])
        @tag = @business.tags.build(tag_params)

        if @tag.save
            redirect_to user_business_path(@business.user_id, @business)
        else
            @comments  = @business.comments
            redirect_to user_business_path(@business.user_id, @business)
        end
    end

    private

    def tag_params
        params.require(:tag).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show]

    def show
        @user = User.find_by(id: params[:id])
        @businesses = Business.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user && @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :phone_number, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end
end

app/views/businesses/all.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bidniz!</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,800" />
        <style>
            #nav {
                background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                height: 50px;
                border-radius: 10px;
                width: auto;

            }
            li {
                display: inline;
                padding: 50px;    
            }

            
            #header {
                text-align: center;
                
            }

            body {
                background: #f6f5f7;

                font-family: 'Montserrat', sans-serif;
            }

            .container {
	            background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                border-radius: 10px;
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
                        0 10px 10px rgba(0,0,0,0.22);
                margin-top: 20px;
                width: auto;
                height: auto;
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
            }

            a {
                color: #000;
                font-size: 14px;
                text-decoration: none;
                margin: 15px 0;
            }
        </style>
    </head>
    <body>
        <div id="header">
            <h1>Bidniz!</h1>
            <div id="nav">
                <ul>
                <li><%= link_to "Dashboard", user_path(current_user)%></li>
                <li><%= link_to "My Businesses", user_businesses_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </div>
        <div class="container" id="container">
            <% if logged_in? %>
                <h2>All Businesses for Sale </h2>
                <% @businesses.latest.each do |b| %>
                    <p><%= b.name %></p>
                <% end %>
            <% end %>
        </div>
    </body>
</html>

app/views/businesses/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bidniz!</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,800" />
        <style>
            #nav {
                background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                height: 50px;
                border-radius: 10px;
                width: auto;

            }
            li {
                display: inline;
                padding: 50px;    
            }

            
            #header {
                text-align: center;
                
            }

            body {
                background: #f6f5f7;
                font-family: 'Montserrat', sans-serif;
            }

            .container {
	            background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                border-radius: 10px;
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
                        0 10px 10px rgba(0,0,0,0.22);
                margin-top: 20px;
                width: auto;
                height: auto;
                display: flex;
                align-items: center;
                flex-direction: column;
            }

            a {
                color: #000;
                font-size: 14px;
                text-decoration: none;
            }

            .forms {
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
                height: 100%;
                text-align: center;
                position: relative;
                top: 0;
                height: 100%;
                transition: all 0.6s ease-in-out;
            }

            input {
                background-color: #eee;
                border: none;
                padding: 12px;
                margin: 8px 0;
                width: 100%;
                text-align: center;
            }
            
            .button {
                border-radius: 20px;
                border: 1px solid #FF4B2B;
                background-color: #FFFFFF;
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 1px;
                text-transform: uppercase;
                transition: transform 80ms ease-in;
                width: 300px;
            }

        </style>
    </head>
    <body>
        <div id="header">
            <h1>Bidniz!</h1>
            <div id="nav">
                <ul>
                <li><%= link_to "Dashboard", user_path(current_user)%></li>
                <li><%= link_to "My Businesses", user_businesses_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </div>
        <div class="container" id="container">
            <h2>Edit Your Business</h2>
            <div class="forms">
                <%= form_for (@business) do |f| %>
                    <%= f.hidden_field :user_id %>
                    <%= f.text_field :name, placeholder: "Business Name" %>
                    <br>
                    <%= f.text_field :description, placeholder: "Description" %>
                    <br>
                    <%= f.text_field :address, placeholder: "Address" %>
                    <br>
                    <%= f.number_field :price, placeholder: "Asking Price" %>
                    <br>
                    <%= f.submit "Update Business", :class => "button" %>
                <% end %>
            </div>
        </div>
    </body>
</html>

app/views/businesses/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bidniz!</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,800" />
        <style>
            #nav {
                background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                height: 50px;
                border-radius: 10px;
                width: auto;

            }
            li {
                display: inline;
                padding: 50px;    
            }

            
            #header {
                text-align: center;
                
            }

            body {
                background: #f6f5f7;

                font-family: 'Montserrat', sans-serif;
            }

            .container {
	            background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                border-radius: 10px;
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
                        0 10px 10px rgba(0,0,0,0.22);
                margin-top: 20px;
                width: auto;
                height: auto;
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
            }

            a {
                color: #000;
                font-size: 14px;
                text-decoration: none;
                margin: 15px 0;
            }
        </style>
    </head>
    <body>
        <div id="header">
            <h1>Bidniz!</h1>
            <div id="nav">
                <ul>
                <li><%= link_to "Dashboard", user_path(current_user)%></li>
                <li><%= link_to "My Businesses", user_businesses_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </div>
        <div class="container" id="container">
            <h2>Here is a list of all your businesses for sale:</h2>

            <% @businesses.each do |b| %>
                <h4><%= link_to b.name, user_business_path(current_user, b.id)  %></h4>
                <p>Description: <%= b.description %></p>
                <p>Address: <%= b.address %></p>
                <p>Price: $<%= b.price %></p>
            <% end %>
        </div>
    </body>
</html>

app/views/businesses/new.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bidniz!</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,800" />
        <style>
            #nav {
                background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                height: 50px;
                border-radius: 10px;
                width: auto;

            }
            li {
                display: inline;
                padding: 50px;    
            }

            
            #header {
                text-align: center;
                
            }

            body {
                background: #f6f5f7;
                font-family: 'Montserrat', sans-serif;
            }

            .container {
	            background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                border-radius: 10px;
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
                        0 10px 10px rgba(0,0,0,0.22);
                margin-top: 20px;
                width: auto;
                height: auto;
                display: flex;
                align-items: center;
                flex-direction: column;
            }

            a {
                color: #000;
                font-size: 14px;
                text-decoration: none;
            }

            .forms {
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
                height: 100%;
                text-align: center;
                position: relative;
                top: 0;
                height: 100%;
                transition: all 0.6s ease-in-out;
            }

            input {
                background-color: #eee;
                border: none;
                padding: 12px;
                margin: 8px 0;
                width: 100%;
                text-align: center;
            }
            
            .button {
                border-radius: 20px;
                border: 1px solid #FF4B2B;
                background-color: #FFFFFF;
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 1px;
                text-transform: uppercase;
                transition: transform 80ms ease-in;
                width: 300px;
            }

        </style>
    </head>
    <body>
        <div id="header">
            <h1>Bidniz!</h1>
            <div id="nav">
                <ul>
                <li><%= link_to "Dashboard", user_path(current_user)%></li>
                <li><%= link_to "My Businesses", user_businesses_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </div>
        <div class="container" id="container">
            <h2>Add a business for sale</h2>
            <div class="forms">
                <%= form_for (@business) do |f| %>
                    <%= f.hidden_field :user_id %>
                    <%= f.text_field :name, placeholder: "Business Name" %>
                    <br>
                    <%= f.text_field :description, placeholder: "Description" %>
                    <br>
                    <%= f.text_field :address, placeholder: "Address" %>
                    <br>
                    <%= f.number_field :price, placeholder: "Asking Price" %>
                    <br>
                    <%= f.submit "Create Business", :class => "button" %>
                <% end %>
            </div>
        </div>
    </body>
</html>

app/views/businesses/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bidniz!</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,800" />
        <style>
            #nav {
                background: #FF416C;
                /* background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C); */
                /* background: linear-gradient(to right, #FF4B2B, #FF416C); */
                background-repeat: no-repeat;
                background-size: cover;
                height: 50px;
                border-radius: 10px;
                width: auto;

            }
            li {
                display: inline;
                padding: 50px;    
            }

            
            #header {
                text-align: center;
                
            }

            body {
                background: #f6f5f7;

                font-family: 'Montserrat', sans-serif;
            }

            .container {
	            background: #FF416C; */
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C); */
                background: linear-gradient(to right, #FF4B2B, #FF416C); */
                background-repeat: no-repeat;
                background-size: cover;
                border-radius: 10px;
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
                        0 10px 10px rgba(0,0,0,0.22);
                margin-top: 20px;
                width: auto;
                height: auto;
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
            }

            a {
                color: #000;
                font-size: 14px;
                text-decoration: none;
                margin: 15px 0;
            }

            button {
                border-radius: 20px;
                border: 1px solid #FF4B2B;
                background-color: #FFFFFF;
                font-size: 12px;
                font-weight: bold;
                padding: 10px 25px;
                letter-spacing: 1px;
                text-transform: uppercase;
                transition: transform 80ms ease-in;
            }

            #ajax-comment-data {
                text-align: center;
            }

            #ajax-new-comment {
                text-align: center;
            }

        </style>
    </head>
    <body>
        <div id="header">
            <h1>Bidniz!</h1>
            <div id="nav">
                <ul>
                <li><%= link_to "Dashboard", user_path(current_user)%></li>
                <li><%= link_to "My Businesses", user_businesses_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </div>
        <div class="container" id="container">
            <h3>Business Details: </h3>

            <p>Name: <%= @business.name %></p>
            <p>Description: <%= @business.description %></p>

            <button id="businesses-more-info" data-id="<%= @business.id %>"> More Info </button>
            <br>
            <div id='ajax-additional-info'> </div>

            <!--
            <% # View and Add Tags %>
            <h2>Tags</h2>
            <% @business.tags.each do |t| %>
                <p><%= t.name if t.name %></p>
            <% end %>

            <%= form_for([@business, @business.tags.build]) do |f| %>

                <p><%= f.label "Add a tag" %></p>
                <%= f.text_field :name %>
                <br>
                <%= f.submit %>

            <% end %>
            -->

            <% if @business.user_id == current_user.id %>
                <h4><%= link_to "Edit", edit_business_path(@business) %></h4>
            <% end %>

            <% if @business.user_id == current_user.id%>
                <h4><%= link_to "Delete Business", business_path(@business), method: :delete, data: { confirm: "Are you sure you want to take this business off the market?" }%></h4>
            <% end %>

            <button id="view-comments" data-id="<%= @business.id %>"> View Comments </button>
            <br>
            <div id='ajax-comment-data'> </div>

            <!--
            <h2>Comments</h2>
            <% @comments.each do |c| %>
                <p><%= link_to c.user.name, user_path(c.user_id) %>: <%= c.content %></p>
            <% end %>
            -->
            
            <%= form_for([@business, @business.comments.build]) do |f| %>

                <p><%= f.label "Reply to thread" %></p>
                <%= f.text_area :content %>
                <br>
                <%= f.submit %>

            <% end %>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BidnizApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bidniz!</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,800" />
        <style>
            #nav {
                background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                height: 50px;
                border-radius: 10px;
                width: auto;

            }
            li {
                display: inline;
                padding: 50px;    
            }

            
            #header {
                text-align: center;
                
            }

            body {
                background: #f6f5f7;

                font-family: 'Montserrat', sans-serif;
            }

            .container {
	            background: #FF416C;
                background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
                background: linear-gradient(to right, #FF4B2B, #FF416C);
                background-repeat: no-repeat;
                background-size: cover;
                border-radius: 10px;
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
                        0 10px 10px rgba(0,0,0,0.22);
                margin-top: 20px;
                width: auto;
                height: auto;
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
            }

            a {
                color: #000;
                font-size: 14px;
                text-decoration: none;
                margin: 15px 0;
            }

                        button {
                border-radius: 20px;
                border: 1px solid #FF4B2B;
                background-color: #FFFFFF;
                font-size: 12px;
                font-weight: bold;
                padding: 10px 25px;
                letter-spacing: 1px;
                text-transform: uppercase;
                transition: transform 80ms ease-in;
            }

            #ajax-businesses {
                text-align: center;
            }

            .link_button {
                border-radius: 10px;
                border: 1px solid #FF4B2B;
                background-color: #FFFFFF;
                font-size: 8px;
                font-weight: bold;
                padding: 5px 5px;
                letter-spacing: 1px;
                transition: transform 80ms ease-in;
            }

        </style>
    </head>
    <body>
        <div id="header">
            <h1>Bidniz!</h1>
            <div id="nav">
                <ul>
                <li><%= link_to "Dashboard", user_path(current_user)%></li>
                <li><%= link_to "My Businesses", user_businesses_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </div>
        <div class="container" id="container">
            <% if current_user != @user %>
                <h2>You are logged in as <%= current_user.name %>(<%= current_user.email%>)!</h2>
                <h3>You are viewing <%= @user.name %>'s profile </h3>
                <h4><%= @user.name %>'s Businesses for Sale:</h4>

                <% @user.businesses.each do |b| %>
                    <h4><%= link_to b.name, user_business_path(@user, b.id)  %></h4>
                    <p>Description: <%= b.description %></p>
                    <p>Address: <%= b.address %></p>
                    <p>Price: <%= b.price %></p>
                <% end %>
                <%= link_to "Go Back to Dashboard", user_path(current_user)%>
            <% end %>

            <% if logged_in? && current_user == @user %>
                <h2>Welcome to Your Dashboard, <%= current_user.name %>!</h2>
                <p><%= link_to "View All Your Businesses For Sale", user_businesses_path(current_user) %><p>
                <p><%= link_to "Sell A Business", new_business_path %><p>

                <h3>Recent Businesses for Sale </h3>

                <button id='businesses-data'> Show Businesses </button>
                <div id='ajax-businesses'> </div>
                <br>
                <br>
            <% end %>
        </div>
    </body>
</html>